{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_verifyloginfunctionality[logInCredentialData0]", "rerun": "0"}, "1": {"status": "FAIL", "message": "   AttributeError: type object 'TestLoginTestCases' has no attribute 'self'\n", "test_name": "test_verifycustomersupport", "rerun": "0"}}, "suite_name": "test_custsupport.py"}}}, "date": "March 29, 2022", "start_time": 1648578092.0262163, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}